---
- hosts: mysql1.local
  become: true
  roles:
  - setup
  - db
  - backup-percona
  vars:
    root_password: secret_password
    mysql:
      database: test-db
      user: dbadmin
      password: foobar
      privileges: '*.*:ALL'
      host: '%'
      bind: '0.0.0.0'
